/*
 * HTML Pages — Embedded web pages served by the HTTP server.
 *
 * Separated from http_server.c for maintainability.
 * Included once from http_server.c (not a public header).
 */

#ifndef HTML_PAGES_H_
#define HTML_PAGES_H_

/* Index HTML page — MJPEG stream view with HUD overlay */
static const char index_html[] =
	"<!DOCTYPE html><html><head>"
	"<meta charset=\"utf-8\">"
	"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
	"<title>ESP32-CAM</title>"
	"<style>"
	"body{font-family:sans-serif;text-align:center;background:#1a1a2e;color:#eee;margin:0;padding:20px}"
	"h1{color:#0ff;margin:10px 0}img{max-width:100%;border:2px solid #0ff;border-radius:8px}"
	".hud{background:#16213e;padding:10px;border-radius:8px;margin:10px auto;max-width:420px;"
	"display:flex;flex-wrap:wrap;justify-content:center;gap:8px;font-size:0.9em}"
	".hud span{background:#0d1b2a;padding:4px 10px;border-radius:4px}"
	".btn{background:#0ff;color:#1a1a2e;border:none;padding:8px 20px;border-radius:6px;"
	"font-size:1em;cursor:pointer;margin:8px}.btn:hover{background:#0aa}"
	"</style></head><body>"
	"<h1>&#x1F4F7; ESP32-CAM</h1>"
	"<div class=\"hud\" id=\"hud\">"
	"<span id=\"fps\">FPS: --</span>"
	"<span id=\"temp\">Temp: --</span>"
	"<span id=\"up\">Up: --</span>"
	"<span id=\"led\">LED: --</span>"
	"<span id=\"rssi\">WiFi: --</span>"
	"<span id=\"mem\">Heap: --</span>"
	"<span id=\"res_hud\">Res: --</span>"
	"</div>"
	"<img src=\"\" id=\"cam\" alt=\"MJPEG Stream\">"
	"<br>"
	"<button class=\"btn\" onclick=\"ledCtrl('on')\">LED ON</button>"
	"<button class=\"btn\" onclick=\"ledCtrl('off')\">LED OFF</button>"
	"<button class=\"btn\" onclick=\"ledCtrl('toggle')\">Toggle</button>"
	"<button class=\"btn\" onclick=\"snap()\">Snapshot</button>"
	"<br>"
	"<select class=\"btn\" id=\"res\" onchange=\"setRes(this.value)\">"
	"<option value=\"qvga\">QVGA 320x240</option>"
	"<option value=\"vga\">VGA 640x480</option>"
	"<option value=\"svga\">SVGA 800x600</option>"
	"<option value=\"xga\">XGA 1024x768</option>"
	"<option value=\"sxga\">SXGA 1280x1024</option>"
	"<option value=\"uxga\">UXGA 1600x1200</option>"
	"</select>"
	"<br><a style=\"color:#0ff\" href=\"/ws\">WebSocket view</a>"
	"<script>"
	"function upd(){"
	"fetch('/api/status').then(r=>r.json()).then(d=>{"
	"document.getElementById('fps').textContent='FPS: '+(d.fps/10);"
	"document.getElementById('temp').textContent='Temp: '+(d.temp/10)+'\\u00b0C';"
	"var s=d.uptime,m=Math.floor(s/60),h=Math.floor(m/60);"
	"document.getElementById('up').textContent='Up: '+h+'h'+m%60+'m';"
	"document.getElementById('led').textContent='LED: '+d.led;"
	"document.getElementById('rssi').textContent='WiFi: '+d.rssi+'dBm ch'+d.channel;"
	"document.getElementById('mem').textContent='Heap: '+(d.heap_free/1024|0)+'KB free';"
	"if(d.resolution){"
	"document.getElementById('res_hud').textContent='Res: '+d.resolution;"
	"var sel=document.getElementById('res');"
	"if(sel&&sel.value!=d.resolution.toLowerCase())sel.value=d.resolution.toLowerCase()}"
	"}).catch(()=>{})};"
	"function setRes(r){"
	"fetch('/api/resolution/'+r).then(r=>r.json()).then(d=>{"
	"document.getElementById('res_hud').textContent='Res: '+d.resolution;"
	"var cam=document.getElementById('cam');"
	"cam.src='';setTimeout(function(){"
	"cam.src='http://'+location.hostname+':'+(parseInt(location.port||80)+1)+'/stream/tcp?t='+Date.now()},1000)"
	"}).catch(()=>{})};"
	"function ledCtrl(a){"
	"fetch('/api/led/'+a).then(r=>r.json()).then(d=>{"
	"document.getElementById('led').textContent='LED: '+d.led;"
	"}).catch(()=>{})};"
	"function snap(){"
	"var u='http://'+location.hostname+':'+(parseInt(location.port||80)+1)+"
	"'/snapshot.jpg?t='+Date.now();"
	"window.open(u,'_blank')};"
	"setInterval(upd,2000);upd();"
	"document.getElementById('cam').src='http://'+location.hostname+':'+("
	"parseInt(location.port||80)+1)+'/stream/tcp';"
	"</script></body></html>";

/* WebSocket stream page — Canvas + JS */
static const char ws_page_html[] =
	"<!DOCTYPE html><html><head>"
	"<meta charset=\"utf-8\">"
	"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
	"<title>ESP32-CAM WS</title>"
	"<style>"
	"body{font-family:sans-serif;text-align:center;background:#1a1a2e;color:#eee;margin:0;padding:20px}"
	"h1{color:#0ff;margin:10px 0}canvas{max-width:100%;border:2px solid #0ff;border-radius:8px}"
	".hud{background:#16213e;padding:10px;border-radius:8px;margin:10px auto;max-width:420px;"
	"display:flex;flex-wrap:wrap;justify-content:center;gap:8px;font-size:0.9em}"
	".hud span{background:#0d1b2a;padding:4px 10px;border-radius:4px}"
	"a{color:#0ff}"
	"</style></head><body>"
	"<h1>&#x1F4F7; ESP32-CAM <small>WebSocket</small></h1>"
	"<div class=\"hud\" id=\"hud\">"
	"<span id=\"fps\">FPS: --</span>"
	"<span id=\"sz\">Size: --</span>"
	"<span id=\"st\">WS: connecting</span>"
	"</div>"
	"<canvas id=\"c\" width=\"320\" height=\"240\"></canvas>"
	"<br><a href=\"/\">MJPEG view</a>"
	"<script>"
	"var c=document.getElementById('c'),ctx=c.getContext('2d'),"
	"fc=0,t0=Date.now(),ws;"
	"function conn(){"
	"ws=new WebSocket('ws://'+location.hostname+':'+("
	"parseInt(location.port||80)+1)+'/stream/ws');"
	"ws.binaryType='arraybuffer';"
	"ws.onopen=function(){document.getElementById('st').textContent='WS: open'};"
	"ws.onclose=function(){document.getElementById('st').textContent='WS: closed';"
	"setTimeout(conn,2000)};"
	"ws.onerror=function(){ws.close()};"
	"ws.onmessage=function(e){"
	"var blob=new Blob([e.data],{type:'image/jpeg'});"
	"var url=URL.createObjectURL(blob);"
	"var img=new Image();img.onload=function(){"
	"c.width=img.width;c.height=img.height;"
	"ctx.drawImage(img,0,0);URL.revokeObjectURL(url);"
	"fc++;var el=(Date.now()-t0)/1000;"
	"if(el>0)document.getElementById('fps').textContent='FPS: '+(fc/el).toFixed(1);"
	"document.getElementById('sz').textContent='Size: '+(e.data.byteLength/1024).toFixed(1)+'KB';"
	"};img.src=url}};"
	"conn();"
	"</script></body></html>";

#endif /* HTML_PAGES_H_ */
